import {
  CETH_ABI,
  CETH_ADDRESS,
  CUSDT_ABI,
  CUSDT_ADDRESS,
  STAKING_ABI,
  STAKING_ADDRESS,
} from './deployments';

export { CETH_ABI, CETH_ADDRESS, CUSDT_ABI, CUSDT_ADDRESS, STAKING_ABI, STAKING_ADDRESS };

