import { task } from "hardhat/config";
import type { TaskArguments } from "hardhat/types";
import { FhevmType } from "@fhevm/hardhat-plugin";
import { ethers } from "ethers";
import fs from "node:fs";
import path from "node:path";

type DeploymentJson = {
  address: string;
  abi: unknown[];
};

function isZeroHandle(handle: string): boolean {
  return handle === ethers.ZeroHash;
}

task("encryptfi:addresses", "Print EncryptFi contract addresses").setAction(async function (
  _taskArguments: TaskArguments,
  hre,
) {
  const { deployments } = hre;

  const cEth = await deployments.get("ERC7984ETH");
  const cUsdt = await deployments.get("ERC7984USDT");
  const staking = await deployments.get("EncryptFiStaking");

  console.log(`ERC7984ETH      : ${cEth.address}`);
  console.log(`ERC7984USDT     : ${cUsdt.address}`);
  console.log(`EncryptFiStaking: ${staking.address}`);
});

task("encryptfi:balances", "Decrypt cETH/cUSDT wallet + staking balances")
  .addOptionalParam("user", "User address (defaults to the first signer)")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const { deployments, fhevm } = hre;

    await fhevm.initializeCLIApi();

    const cEthDep = await deployments.get("ERC7984ETH");
    const cUsdtDep = await deployments.get("ERC7984USDT");
    const stakingDep = await deployments.get("EncryptFiStaking");

    const signers = await hre.ethers.getSigners();
    const signer = signers[0];
    const user = (taskArguments.user as string | undefined) ?? signer.address;

    const cEth = await hre.ethers.getContractAt("ERC7984ETH", cEthDep.address);
    const cUsdt = await hre.ethers.getContractAt("ERC7984USDT", cUsdtDep.address);
    const staking = await hre.ethers.getContractAt("EncryptFiStaking", stakingDep.address);

    const encryptedCethBal = await cEth.confidentialBalanceOf(user);
    const encryptedCusdtBal = await cUsdt.confidentialBalanceOf(user);
    const encryptedStakedCeth = await staking.confidentialStakedCETHOf(user);
    const encryptedStakedCusdt = await staking.confidentialStakedCUSDTOf(user);

    const clearCethBal = isZeroHandle(encryptedCethBal)
      ? 0n
      : await fhevm.userDecryptEuint(FhevmType.euint64, encryptedCethBal, cEthDep.address, signer);
    const clearCusdtBal = isZeroHandle(encryptedCusdtBal)
      ? 0n
      : await fhevm.userDecryptEuint(FhevmType.euint64, encryptedCusdtBal, cUsdtDep.address, signer);
    const clearStakedCeth = isZeroHandle(encryptedStakedCeth)
      ? 0n
      : await fhevm.userDecryptEuint(FhevmType.euint64, encryptedStakedCeth, stakingDep.address, signer);
    const clearStakedCusdt = isZeroHandle(encryptedStakedCusdt)
      ? 0n
      : await fhevm.userDecryptEuint(FhevmType.euint64, encryptedStakedCusdt, stakingDep.address, signer);

    console.log(`user            : ${user}`);
    console.log(`cETH balance    : ${clearCethBal}`);
    console.log(`cUSDT balance   : ${clearCusdtBal}`);
    console.log(`staked cETH     : ${clearStakedCeth}`);
    console.log(`staked cUSDT    : ${clearStakedCusdt}`);
  });

task("encryptfi:sync-ui", "Generate ui/src/config/deployments.ts from deployments/<network>")
  .addOptionalParam("networkName", "Hardhat-deploy network folder name (defaults to sepolia)")
  .setAction(async function (taskArguments: TaskArguments, hre) {
    const networkName = (taskArguments.networkName as string | undefined) ?? "sepolia";

    const root = hre.config.paths.root;
    const deploymentsDir = path.join(root, "deployments", networkName);

    const cEthPath = path.join(deploymentsDir, "ERC7984ETH.json");
    const cUsdtPath = path.join(deploymentsDir, "ERC7984USDT.json");
    const stakingPath = path.join(deploymentsDir, "EncryptFiStaking.json");

    const missing = [cEthPath, cUsdtPath, stakingPath].filter((p) => !fs.existsSync(p));
    if (missing.length > 0) {
      throw new Error(
        `Missing deployment files for network '${networkName}':\n` + missing.map((p) => `- ${p}`).join("\n"),
      );
    }

    const cEth = JSON.parse(fs.readFileSync(cEthPath, "utf8")) as DeploymentJson;
    const cUsdt = JSON.parse(fs.readFileSync(cUsdtPath, "utf8")) as DeploymentJson;
    const staking = JSON.parse(fs.readFileSync(stakingPath, "utf8")) as DeploymentJson;

    const outPath = path.join(root, "ui", "src", "config", "deployments.ts");
    const contents = `// This file is auto-generated by 'npx hardhat encryptfi:sync-ui'.
// Do not edit manually.

export const CETH_ADDRESS = ${JSON.stringify(cEth.address)} as const;
export const CUSDT_ADDRESS = ${JSON.stringify(cUsdt.address)} as const;
export const STAKING_ADDRESS = ${JSON.stringify(staking.address)} as const;

export const CETH_ABI = ${JSON.stringify(cEth.abi, null, 2)} as const;
export const CUSDT_ABI = ${JSON.stringify(cUsdt.abi, null, 2)} as const;
export const STAKING_ABI = ${JSON.stringify(staking.abi, null, 2)} as const;
`;

    fs.writeFileSync(outPath, contents, "utf8");
    console.log(`Wrote ${outPath}`);
  });
